spring.application.name=HotelManagment

spring.datasource.url=jdbc:postgresql://localhost:5432/temp_database
spring.datasource.username=postgres
spring.datasource.password=PostgreSql0306

spring.jpa.hibernate.ddl-auto=update